# Generated by Django 5.0.6 on 2024-06-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageSteganographyApp', '0002_decryptedimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DecryptedImages',
            new_name='DecryptedImage',
        ),
    ]
